# -*- coding: utf-8 -*-
"""answer_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18fHBbGKpbloeQB1I4rSe2KOpZZe_NpBg
"""

def f(n):
  if n % 2 == 0:
    soln = (n*n) - (2*n) + 3
  else:
    soln = (n**3 - 1) % 7
  return soln

print(f(4))
print(f(5))
print(f(7))
print(f(10))