# -*- coding: utf-8 -*-
"""answer_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vHYEtw_2fU6W1jasHeb7PhdaFzpiinZ-
"""

def clock(input):
  seconds = int(input) % 60
  minutes = int(input // 60)  %  60
  hours = int(input // 60 // 60)
  print( hours, ":", minutes, ":", seconds)

clock(109335)
clock(54543)
clock(360061)