# -*- coding: utf-8 -*-
"""answer_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o9MRC8SQYAoHs39oza7MAoR-CStp1G0_
"""

def name_surname(Name_Surname):
  Name_Surname = Name_Surname.split()
  print("name: ", Name_Surname[0], ",", "surname: ", Name_Surname[1])

name_surname("John Doe")
name_surname("Cmpe 150 ")